version: '3.8'

services:

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      - db
      - api
    networks:
      - todolist_front_network

  api:
    build: ../todolist/.
    depends_on:
      migrations:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - todolist_front_network
      - todolist_db_network
    volumes:
      - ./.docker_env:/code/.env


  migrations:
    build: ../todolist/.
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todolist_db_network
    volumes:
      - ./.docker_env:/code/.env
    command: >
      sh -c "python manage.py makemigrations && 
           python manage.py migrate"

  bot:
    build: ../todolist/.
    depends_on:
      migrations:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    volumes:
      - ./.docker_env:/code/.env
    networks:
      - todolist_db_network
    command: >
      sh -c "python manage.py makemigrations && 
            python manage.py migrate"

  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    networks:
      - todolist_db_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_todolist:/var/lib/postgresql/data



volumes:
  postgres_todolist:


networks:
  todolist_db_network:
  todolist_front_network:
