version: '3.8'

services:

  postgresql:
    image: postgres:14-alpine
    volumes:
      - ../postgres_todolist:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_todolist:

